import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { FileText, ExternalLink, Download, RefreshCw, AlertTriangle, Eye } from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import { PageHeader, StatusPill } from "@/components/dashboard-ui";
import { Button } from "@/components/ui/button";
import { MediaPreview } from "@/components/media-preview";
import { api, absoluteAssetUrl, getApiBaseUrl } from "@/lib/api";
import type { ExecStatus } from "@/lib/types";

type Report = {
  id: string; execId: string; suite: string; environment: string;
  status: ExecStatus; url: string; generatedAt: string; sizeMB?: string | number;
};

export const Route = createFileRoute("/reports")({
  head: () => ({
    meta: [
      { title: "Reports · Playwright Automation" },
      { name: "description", content: "HTML test reports generated by Playwright for each execution." },
    ],
  }),
  component: ReportsPage,
});

function ReportsPage() {
  const [items, setItems] = useState<Report[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [preview, setPreview] = useState<Report | null>(null);

  const load = async () => {
    setLoading(true); setError(null);
    try { setItems(await api.listReports()); }
    catch (e) { setError(e instanceof Error ? e.message : "network error"); setItems([]); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, []);

  return (
    <div className="mx-auto max-w-7xl space-y-6">
      <div className="flex items-start justify-between gap-4">
        <PageHeader title="Reports" description={error
          ? `Cannot reach ${getApiBaseUrl()}/api/reports`
          : `${items.length} HTML reports from ${getApiBaseUrl()}`} />
        <Button variant="outline" size="sm" onClick={load} disabled={loading} className="gap-1.5">
          <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} /> Refresh
        </Button>
      </div>

      {error && (
        <div className="surface-card flex items-start gap-3 border-destructive/40 p-4 text-sm">
          <AlertTriangle className="mt-0.5 h-4 w-4 text-destructive" />
          <div className="text-xs text-muted-foreground">{error}</div>
        </div>
      )}

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {items.map((r) => (
          <div key={r.id} className="surface-card group flex flex-col overflow-hidden">
            <button
              onClick={() => setPreview(r)}
              className="relative flex h-40 items-center justify-center bg-gradient-to-br from-primary/10 via-accent/5 to-transparent"
            >
              <FileText className="h-14 w-14 text-primary/70 transition-transform group-hover:scale-110" />
              <div className="absolute right-3 top-3"><StatusPill status={r.status} /></div>
            </button>
            <div className="flex flex-1 flex-col gap-3 p-4">
              <div>
                <div className="text-sm font-semibold text-foreground">{r.suite}</div>
                <div className="mt-0.5 font-mono text-[11px] text-muted-foreground">{r.execId}</div>
              </div>
              <div className="grid grid-cols-2 gap-2 text-xs text-muted-foreground">
                <div>Env<div className="text-foreground">{r.environment}</div></div>
                {r.sizeMB != null && <div>Size<div className="font-mono text-foreground">{r.sizeMB} MB</div></div>}
                <div className="col-span-2">Generated<div className="text-foreground">{formatDistanceToNow(new Date(r.generatedAt), { addSuffix: true })}</div></div>
              </div>
              <div className="mt-auto flex gap-2 border-t border-border pt-3">
                <Button size="sm" variant="secondary" className="flex-1 gap-1.5" onClick={() => setPreview(r)}>
                  <Eye className="h-3.5 w-3.5" /> Preview
                </Button>
                <Button asChild size="sm" variant="ghost" className="gap-1.5" title="Open in new tab">
                  <a href={absoluteAssetUrl(r.url)} target="_blank" rel="noreferrer"><ExternalLink className="h-3.5 w-3.5" /></a>
                </Button>
                <Button asChild size="sm" variant="ghost" className="gap-1.5" title="Download">
                  <a href={absoluteAssetUrl(r.url)} download><Download className="h-3.5 w-3.5" /></a>
                </Button>
              </div>
            </div>
          </div>
        ))}
        {items.length === 0 && !loading && !error && (
          <div className="col-span-full surface-card p-12 text-center text-sm text-muted-foreground">No reports yet.</div>
        )}
      </div>

      <MediaPreview
        open={!!preview}
        onOpenChange={(o) => !o && setPreview(null)}
        title={preview ? `${preview.suite} report` : ""}
        subtitle={preview && <><span className="font-mono">{preview.execId}</span> · {preview.environment}</>}
        url={preview?.url ?? ""}
        kind="iframe"
      />
    </div>
  );
}
