/**
 * @fileoverview Artifact scanner service.
 *
 * After a Playwright execution completes, this service scans the framework's
 * output directories (playwright-report/, test-results/) for generated artifacts,
 * copies them into the backend's uploads/ directory, and returns frontend-compatible
 * metadata objects.
 *
 * @module services/artifactScanner
 */

const path = require('node:path');
const { nanoid } = require('nanoid');
const config = require('../config');
const { ARTIFACT_TYPES, EXT_TO_ARTIFACT } = require('../utils/constants');
const { listFilesRecursive, copyArtifact, ensureDir, getFileSize, formatFileSize, pathExists } = require('../utils/fileHelper');
const logger = require('../utils/logger');

// ── In-memory artifact registries ────────────────────────────────────────────

/** @type {Object[]} */
const reports = [];
/** @type {Object[]} */
const screenshots = [];
/** @type {Object[]} */
const videos = [];
/** @type {Object[]} */
const traces = [];

// ── Directory mappings ───────────────────────────────────────────────────────

const UPLOAD_DIRS = {
  [ARTIFACT_TYPES.REPORT]: path.join(config.uploadsDir, 'reports'),
  [ARTIFACT_TYPES.SCREENSHOT]: path.join(config.uploadsDir, 'screenshots'),
  [ARTIFACT_TYPES.VIDEO]: path.join(config.uploadsDir, 'videos'),
  [ARTIFACT_TYPES.TRACE]: path.join(config.uploadsDir, 'traces'),
};

/**
 * Classify a file by its extension.
 *
 * @param {string} filePath
 * @returns {string|null} Artifact type or null if unrecognised.
 */
function classifyFile(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  return EXT_TO_ARTIFACT[ext] || null;
}

/**
 * Extract a test name from a file path.
 * Best-effort: strips directories and extensions, replaces separators.
 *
 * @param {string} filePath - Absolute path to the artifact file.
 * @returns {string}
 */
function extractTestName(filePath) {
  const base = path.basename(filePath, path.extname(filePath));
  return base
    .replace(/[-_]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Scan the Playwright framework's output directories for artifacts
 * generated by a specific execution, copy them into uploads/, and
 * register metadata.
 *
 * @param {string} execId      - Execution ID.
 * @param {string} suite       - Suite name.
 * @param {string} environment - "QA" or "Production".
 * @param {string} status      - Final execution status.
 */
async function scanAndRegister(execId, suite, environment, status) {
  const frameworkRoot = config.playwrightProjectPath;

  // Directories to scan (Playwright default output locations).
  const scanDirs = [
    path.join(frameworkRoot, 'playwright-report'),
    path.join(frameworkRoot, 'test-results'),
  ];

  for (const dir of scanDirs) {
    const exists = await pathExists(dir);
    if (!exists) {
      logger.debug(`[Artifacts] Directory not found: ${dir}`);
      continue;
    }

    const files = await listFilesRecursive(dir);
    logger.info(`[Artifacts] Found ${files.length} files in ${dir}`);

    for (const filePath of files) {
      const type = classifyFile(filePath);
      if (!type) continue;

      try {
        await registerArtifact(filePath, type, execId, suite, environment, status);
      } catch (err) {
        logger.warn(`[Artifacts] Failed to register ${filePath}: ${err.message}`);
      }
    }
  }
}

/**
 * Copy a single artifact file into uploads/ and register its metadata.
 *
 * @param {string} srcPath     - Absolute source file path.
 * @param {string} type        - Artifact type (report, screenshot, video, trace).
 * @param {string} execId      - Execution ID.
 * @param {string} suite       - Suite name.
 * @param {string} environment - Environment.
 * @param {string} status      - Execution status.
 */
async function registerArtifact(srcPath, type, execId, suite, environment, status) {
  const destDir = UPLOAD_DIRS[type];
  if (!destDir) return;

  await ensureDir(destDir);

  const ext = path.extname(srcPath);
  const filename = `${execId}_${nanoid(6)}${ext}`;
  const destPath = path.join(destDir, filename);

  await copyArtifact(srcPath, destPath);

  const size = await getFileSize(destPath);
  const url = `/uploads/${type}s/${filename}`;
  const testName = extractTestName(srcPath);
  const now = new Date().toISOString();

  const metadata = {
    id: `${type[0]}${nanoid(5)}`,
    execId,
    test: testName,
    url,
    takenAt: now,
  };

  switch (type) {
    case ARTIFACT_TYPES.REPORT:
      reports.push({
        ...metadata,
        suite,
        environment,
        status,
        generatedAt: now,
        sizeMB: (size / (1024 * 1024)).toFixed(2),
      });
      break;

    case ARTIFACT_TYPES.SCREENSHOT:
      screenshots.push(metadata);
      break;

    case ARTIFACT_TYPES.VIDEO:
      videos.push({
        ...metadata,
        duration: '', // Duration detection would require ffprobe — left as future enhancement.
      });
      break;

    case ARTIFACT_TYPES.TRACE:
      traces.push({
        ...metadata,
        size: formatFileSize(size),
      });
      break;
  }

  logger.debug(`[Artifacts] Registered ${type}: ${filename} for ${execId}`);
}

// ── Public accessors (return frontend-compatible arrays) ─────────────────────

/**
 * List all registered reports.
 * @returns {Object[]}
 */
function listReports() {
  return reports.map((r) => ({ ...r }));
}

/**
 * List all registered screenshots.
 * @returns {Object[]}
 */
function listScreenshots() {
  return screenshots.map((s) => ({ ...s }));
}

/**
 * List all registered videos.
 * @returns {Object[]}
 */
function listVideos() {
  return videos.map((v) => ({ ...v }));
}

/**
 * List all registered traces.
 * @returns {Object[]}
 */
function listTraces() {
  return traces.map((t) => ({ ...t }));
}

/**
 * Remove all artifacts associated with an execution ID.
 *
 * @param {string} execId
 */
function removeByExecId(execId) {
  const filter = (arr) => {
    for (let i = arr.length - 1; i >= 0; i--) {
      if (arr[i].execId === execId) arr.splice(i, 1);
    }
  };
  filter(reports);
  filter(screenshots);
  filter(videos);
  filter(traces);
}

module.exports = {
  scanAndRegister,
  listReports,
  listScreenshots,
  listVideos,
  listTraces,
  removeByExecId,
};
