/**
 * @fileoverview Artifact scanner service.
 *
 * After a Playwright execution completes, this service scans the framework's
 * output directories (playwright-report/, test-results/) for generated artifacts,
 * copies them into the backend's uploads/ directory, and returns frontend-compatible
 * metadata objects.
 *
 * @module services/artifactScanner
 */

const path = require('node:path');
const fs = require('node:fs');
const { nanoid } = require('nanoid');
const config = require('../config');
const { ARTIFACT_TYPES, EXT_TO_ARTIFACT } = require('../utils/constants');
const { listFilesRecursive, copyArtifact, ensureDir, getFileSize, formatFileSize, pathExists } = require('../utils/fileHelper');
const logger = require('../utils/logger');
const Artifact = require('../models/Artifact');

// ── Directory mappings ───────────────────────────────────────────────────────

const UPLOAD_DIRS = {
  [ARTIFACT_TYPES.REPORT]: path.join(config.uploadsDir, 'reports'),
  [ARTIFACT_TYPES.SCREENSHOT]: path.join(config.uploadsDir, 'screenshots'),
  [ARTIFACT_TYPES.VIDEO]: path.join(config.uploadsDir, 'videos'),
  [ARTIFACT_TYPES.TRACE]: path.join(config.uploadsDir, 'traces'),
};

/**
 * Classify a file by its extension.
 *
 * @param {string} filePath
 * @returns {string|null} Artifact type or null if unrecognised.
 */
function classifyFile(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  return EXT_TO_ARTIFACT[ext] || null;
}

/**
 * Extract a test name from a file path.
 * Best-effort: strips directories and extensions, replaces separators.
 *
 * @param {string} filePath - Absolute path to the artifact file.
 * @returns {string}
 */
function extractTestName(filePath) {
  const base = path.basename(filePath, path.extname(filePath));
  return base
    .replace(/[-_]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Scan the Playwright framework's output directories for artifacts
 * generated by a specific execution, copy them into uploads/, and
 * register metadata.
 *
 * @param {string} execId      - Execution ID.
 * @param {string} suite       - Suite name.
 * @param {string} environment - "QA" or "Production".
 * @param {string} status      - Final execution status.
 */
async function scanAndRegister(execId, suite, environment, status) {
  const frameworkRoot = config.playwrightProjectPath;

  // Directories to scan (Playwright default output locations).
  const scanDirs = [
    path.join(frameworkRoot, 'playwright-report'),
    path.join(frameworkRoot, 'test-results'),
  ];

  for (const dir of scanDirs) {
    const exists = await pathExists(dir);
    if (!exists) {
      logger.debug(`[Artifacts] Directory not found: ${dir}`);
      continue;
    }

    const files = await listFilesRecursive(dir);
    logger.info(`[Artifacts] Found ${files.length} files in ${dir}`);

    for (const filePath of files) {
      const type = classifyFile(filePath);
      if (!type) continue;

      try {
        await registerArtifact(filePath, type, execId, suite, environment, status);
      } catch (err) {
        logger.warn(`[Artifacts] Failed to register ${filePath}: ${err.message}`);
      }
    }
  }
}

/**
 * Copy a single artifact file into uploads/ and register its metadata.
 *
 * @param {string} srcPath     - Absolute source file path.
 * @param {string} type        - Artifact type (report, screenshot, video, trace).
 * @param {string} execId      - Execution ID.
 * @param {string} suite       - Suite name.
 * @param {string} environment - Environment.
 * @param {string} status      - Execution status.
 */
async function registerArtifact(srcPath, type, execId, suite, environment, status) {
  const destDir = UPLOAD_DIRS[type];
  if (!destDir) return;

  await ensureDir(destDir);

  const ext = path.extname(srcPath);
  const filename = `${execId}_${nanoid(6)}${ext}`;
  const destPath = path.join(destDir, filename);

  await copyArtifact(srcPath, destPath);

  const size = await getFileSize(destPath);
  const url = `/uploads/${type}s/${filename}`;
  const testName = extractTestName(srcPath);
  const now = new Date().toISOString();

  const metadata = {
    id: `${type[0]}${nanoid(5)}`,
    execId,
    type,
    test: testName,
    url,
    takenAt: now,
  };

  switch (type) {
    case ARTIFACT_TYPES.REPORT:
      metadata.suite = suite;
      metadata.environment = environment;
      metadata.status = status;
      metadata.generatedAt = now;
      metadata.sizeMB = (size / (1024 * 1024)).toFixed(2);
      break;
    case ARTIFACT_TYPES.VIDEO:
      metadata.duration = ''; // Duration detection would require ffprobe — left as future enhancement.
      break;
    case ARTIFACT_TYPES.TRACE:
      metadata.size = formatFileSize(size);
      break;
  }

  await Artifact.create(metadata);

  logger.debug(`[Artifacts] Registered ${type}: ${filename} for ${execId}`);
}

// ── Public accessors (return frontend-compatible arrays) ─────────────────────

function formatArtifact(doc) {
  const raw = typeof doc.toObject === 'function' ? doc.toObject() : doc;
  // Strip mongoose internal fields and the 'type' field from response if necessary, 
  // but keeping it is fine. The frontend might not care about 'type' or just ignores it.
  return raw;
}

/**
 * List all registered reports.
 * @returns {Promise<Object[]>}
 */
async function listReports() {
  const docs = await Artifact.find({ type: ARTIFACT_TYPES.REPORT }).sort({ takenAt: -1 }).lean().exec();
  return docs.map(formatArtifact);
}

/**
 * List all registered screenshots.
 * @returns {Promise<Object[]>}
 */
async function listScreenshots() {
  const docs = await Artifact.find({ type: ARTIFACT_TYPES.SCREENSHOT }).sort({ takenAt: -1 }).lean().exec();
  return docs.map(formatArtifact);
}

/**
 * List all registered videos.
 * @returns {Promise<Object[]>}
 */
async function listVideos() {
  const docs = await Artifact.find({ type: ARTIFACT_TYPES.VIDEO }).sort({ takenAt: -1 }).lean().exec();
  return docs.map(formatArtifact);
}

/**
 * List all registered traces.
 * @returns {Promise<Object[]>}
 */
async function listTraces() {
  const docs = await Artifact.find({ type: ARTIFACT_TYPES.TRACE }).sort({ takenAt: -1 }).lean().exec();
  return docs.map(formatArtifact);
}

/**
 * Remove an artifact from DB and filesystem.
 */
async function removeArtifact(artifact) {
  try {
    // Delete from DB
    await Artifact.deleteOne({ id: artifact.id }).exec();
    
    // Delete file from disk
    const typeDir = UPLOAD_DIRS[artifact.type];
    if (typeDir && artifact.url) {
      const filename = path.basename(artifact.url);
      const filePath = path.join(typeDir, filename);
      if (await pathExists(filePath)) {
        await fs.promises.unlink(filePath);
      }
    }
  } catch (err) {
    logger.error(`[Artifacts] Failed to remove artifact ${artifact.id}`, err);
  }
}

/**
 * Remove all artifacts associated with an execution ID.
 *
 * @param {string} execId
 * @returns {Promise<number>} Number of artifacts removed
 */
async function removeByExecId(execId) {
  const artifacts = await Artifact.find({ execId }).lean().exec();
  let count = 0;
  for (const artifact of artifacts) {
    await removeArtifact(artifact);
    count++;
  }
  return count;
}

/**
 * Remove all artifacts associated with multiple execution IDs.
 *
 * @param {string[]} execIds
 * @returns {Promise<number>}
 */
async function removeByExecIds(execIds) {
  const artifacts = await Artifact.find({ execId: { $in: execIds } }).lean().exec();
  let count = 0;
  for (const artifact of artifacts) {
    await removeArtifact(artifact);
    count++;
  }
  return count;
}

/**
 * Remove all artifacts.
 *
 * @returns {Promise<number>}
 */
async function removeAll() {
  const artifacts = await Artifact.find({}).lean().exec();
  let count = 0;
  for (const artifact of artifacts) {
    await removeArtifact(artifact);
    count++;
  }
  return count;
}

module.exports = {
  scanAndRegister,
  listReports,
  listScreenshots,
  listVideos,
  listTraces,
  removeByExecId,
  removeByExecIds,
  removeAll,
};
