/** Manages Test Evidence insertion into MongoDB after execution. */

const path = require('node:path');
const fs = require('node:fs').promises;
const TestEvidence = require('../models/TestEvidence');
const logger = require('../utils/logger');

/**
 * Reads the evidence metadata generated by EvidenceReporter and saves it to MongoDB.
 * @param {string} execId The Execution ID
 */
async function processExecution(execId) {
  try {
    const metadataPath = path.resolve(__dirname, '../../../backend/storage/executions', execId, 'evidence-metadata.json');
    
    const fileExists = await fs.access(metadataPath).then(() => true).catch(() => false);
    
    if (!fileExists) {
      logger.warn(`[EvidenceManager] No evidence metadata found for ${execId} at ${metadataPath}`);
      return;
    }
    
    const metadataContent = await fs.readFile(metadataPath, 'utf8');
    const records = JSON.parse(metadataContent);
    
    if (!records || records.length === 0) {
      logger.info(`[EvidenceManager] No test evidence records to process for ${execId}`);
      return;
    }
    
    await TestEvidence.insertMany(records);
    logger.info(`[EvidenceManager] Successfully processed ${records.length} evidence records for ${execId}`);
    
  } catch (err) {
    logger.error(`[EvidenceManager] Failed to process evidence for ${execId}: ${err.message}`, err);
  }
}

/** Fetches all evidence records for a given execution. */
async function getEvidenceByExecution(execId) {
  return await TestEvidence.find({ executionId: execId }).lean().exec();
}

/** Removes all evidence records associated with multiple execution IDs. */
async function removeByExecIds(execIds) {
  const result = await TestEvidence.deleteMany({ executionId: { $in: execIds } });
  return result.deletedCount;
}

module.exports = {
  processExecution,
  getEvidenceByExecution,
  removeByExecIds
};
